name: budget
description: weekly budget tracker
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  flutter_launcher_icons: "^0.14.4"
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

dependencies:
  flutter:
    sdk: flutter

  # Used for local storage of balance, categories, history
  shared_preferences: ^2.3.2

  # Cupertino icons (optional, but common)
  cupertino_icons: ^1.0.8


flutter:
  uses-material-design: true

  assets:
    - assets/image/logo.png
